### ISSUE TITLE
where is the dataset for training

### ISSUE THREAD

**Issue by SeekPoint** [murthyrudra/NeuralNER#1]

**Comment by murthyrudra** [comment]
Hi, I have added Dutch, German and Spanish data mentioned in the paper under Data folder in NeuralNERMono folder. English data, however, requires a special license but you can get the annotated data in the web. For Indian languages data, you need to write to FIRE 2014 Shared Task Organizers to obtain the labeled data. We have Marathi in-house data available with us, which you can obtain by filling the form here http://www.cfilt.iitb.ac.in/ner/annotated_corpus/

**Comment by SeekPoint** [comment]
cannot access http://www.cfilt.iitb.ac.in/ner/annotated_corpus/

**Comment by murthyrudra** [comment]
Hi, Please fill the form present here http://www.cfilt.iitb.ac.in/ner/download_data.html The earlier link seems to be broken, will fix it.

**Comment by SeekPoint** [comment]
both of them are broken

**Comment by murthyrudra** [comment]
Hi, due to a server issue the links were broken. The links are working now. Please send a signed and scanned undertaking letter stating that the data will be used only for research purpose and not for commercial purpose. I have added the mail id in the page.
