### ISSUE TITLE
Receiving error "name getlogger is not defined"

### ISSUE THREAD

**Issue by samarohith** [murthyrudra/NeuralNER#3]
I tried using -  import logging, but no change

**Comment by murthyrudra** [comment]
Hi, could you paste stacktrace of the error?

**Comment by samarohith** [comment]
Traceback (most recent call last):
  File "NeuralNERYang.py", line 306, in <module>
    main()
  File "NeuralNERYang.py", line 67, in main
    logger = get_logger("NER")
NameError: name 'get_logger' is not defined

**Comment by murthyrudra** [comment]
Hi, please comment or delete that line. I am gonna do the same. That variable is not being used elsewhere.

**Comment by samarohith** [comment]
Sure,will do!!
