### ISSUE TITLE
Different formats of the dataset

### ISSUE THREAD

**Issue by samarohith** [murthyrudra/NeuralNER#4]
I am using spanish as primary and english as assisting language. Datasets are downloaded the links provided in the readme.

The format for spanish data is :
 Melbourne B-LOC
( O
Australia B-LOC
) O

and the format for english data is :
EU NNP I-NP I-ORG
rejects VBZ I-VP O
German JJ I-NP I-MISC
call NN I-NP O

Do the above work, with the code provided in NeuralNERYang?

**Comment by murthyrudra** [comment]
Hi, please use tab as delimiter. I have hard-coded tab as delimiter in utilsLocal.py line number 54 and 55.

**Comment by samarohith** [comment]
Yeah of course , I ran the same code but I got this error :

Training....
Epoch 1 ( learning rate=0.4000, decay rate=0.1000 (schedule=1)): 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-d5a7bf1db890> in <module>()
    305 
    306 if __name__ == '__main__':
--> 307     main()

1 frames
<ipython-input-3-d5a7bf1db890> in main()
    192 
    193                 optim.zero_grad()
--> 194                 loss, _ = network.loss(x_input, batch_length, current_batch_size, current_max_sequence_length, y_output, mask, y_prev, 0)
    195                 print("hello")
    196                 loss.backward()

/content/modules.py in loss(self, x, length_of_sequence, batchSize, maxLength, target, mask, y_prev, languageId)
    142             count = 0
    143             for i in range(batchSize):
--> 144                 for j in range(length_of_sequence[i].data[0]):
    145                     count = count + 1
    146 

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by samarohith** [comment]
Variables used :
Number of epochs = 2 
Mini-Batch size = 1
Bi-LSTM Hidden size = 300
Features per CNN filter = 15
Minimum ngrams for CNN filter = 1
Maximum ngrams for CNN filter = 9
Initial Learning Rate = 0.4
ner_tag_field_l1 = 1
 ner_tag_field_l2 = 3
gamma , scheduler= default

**Comment by murthyrudra** [comment]
Hi, the issue is with Pytorch version mismatch. The support to access data via `data[0]` is no longer supported and one has to use `item()`. I have updated the code. Please let me know if there is any error.

**Comment by samarohith** [comment]
Now I'm getting this error :


---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-fe23ead2a2e1> in <module>()
    242 
    243 if __name__ == '__main__':
--> 244     main()

5 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in <lambda>(t)
    263             Module: self
    264         """
--> 265         return self._apply(lambda t: t.cuda(device))
    266 
    267     def cpu(self):

RuntimeError: CUDA out of memory. Tried to allocate 4.17 GiB (GPU 0; 11.17 GiB total capacity; 8.07 GiB already allocated; 2.74 GiB free; 31.49 MiB cached)



I know this is related to hardware. I'm currently using GPU and CUDA on google colab. Is there any way to eliminate this error?

**Comment by murthyrudra** [comment]
Hi, one reason could be the size of word embeddings. I create a smaller version of word embedding file containing word embeddings only for those words present in my data (training + test + development). This way the size of LookupTable reduces significantly.

**Comment by murthyrudra** [comment]
Also, `ner_tag_field_l*` should be 1. Looking at your earlier file snippets which you had shared 9th column is word and 1st column is ner field for Spanish and 3 for English.

**Comment by samarohith** [comment]
Now I'm receiving the error :

IndexError                                Traceback (most recent call last)
<ipython-input-9-052a41a78235> in <module>()
    242 
    243 if __name__ == '__main__':
--> 244     main()

1 frames
<ipython-input-9-052a41a78235> in main()
    246             writer.close()
    247 
--> 248         acc, precision, recall, f1 = evaluate(tmp_filename)
    249         print('dev loss: %.2f, dev acc: %.2f%%, precision: %.2f%%, recall: %.2f%%, F1: %.2f%%' % (current_epoch_loss, acc, precision, recall, f1))
    250 

<ipython-input-8-9e5d086a8b79> in evaluate(output_file)
     36         line = fin.readline()
     37         fields = line.split(";")
---> 38         acc = float(fields[0].split(":")[1].strip()[:-1])
     39         precision = float(fields[1].split(":")[1].strip()[:-1])
    40         recall = float(fields[2].split(":")[1].strip()[:-1])

IndexError: list index out of range

Also, the score file which is created looks empty.

**Comment by murthyrudra** [comment]
Hi, Sorry. It's my mistake. You need to create a 'tmp' folder in the
current folder. Sorry, I should have specified that in Readme file.

With Regards,
Rudra Murthy

**Comment by samarohith** [comment]
No, I changed that code for my convenience  to :
score_file = "/content/score_%s" % str(uid)   

 The file gets created but looks empty. Is it necessary to cerate a folder called 'tmp' ?

**Comment by murthyrudra** [comment]
No, it's not required to create `tmp` folder. Can you check if there are output files created in `save_dir` folder. Also check the permissions of `eval/conll03eval.v2`. It might not have execute permissions.

**Comment by samarohith** [comment]
I actually have all my files in a single folder. Is that going to be a problem? What permissions are required for conll03eval.v2 ?

**Comment by murthyrudra** [comment]
That shouldn't be a problem. Try running `chmod +x eval/conll03eval.v2` should resolve the error.

**Comment by samarohith** [comment]
Thanks for the help. I have run it successfully on spanish data as primary and English as assisting language and obtained  : test acc: 91.13%, precision: 63.65%, recall: 30.99%, F1: 41.69%
