### ISSUE TITLE
Error in NeuralNERAllShared.py

### ISSUE THREAD

**Issue by samarohith** [murthyrudra/NeuralNER#5]
Recieved Error :

<ipython-input-5-7bbdaea89948> in main()
     82     use_gpu = torch.cuda.is_available()
     83 
---> 84     network = BiCNNLSTMTranstion(vocabularySize, embeddingDimension, min_filter_width, max_filter_width, len(charVocabulary), num_filters, hidden_size, len(tagVocabulary) , embedd_dict, beta)
     85 
     86     lr = learning_rate

/content/modules.py in __init__(self, vocabularySize, embedDimension, minNgrams, maxNgrams, charInputDim, charOutDim, hiddenDim, tagSize, init_embedding, tagSizeAux)
     79         self.logsoftmax = nn.LogSoftmax(dim=1)
     80         self.nll_loss = nn.NLLLoss(size_average=True, reduce=False)
---> 81 
     82         self.language_weight = language_weight
     83 

/content/modules.py in __init__(self, inputDimension, outputDimension)
     41 
     42         self.inputDimension = inputDimension
---> 43         self.outputDimension = outputDimension
     44 
     45         self.linear = nn.Linear(self.inputDimension, self.outputDimension, bias = False)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py in __init__(self, in_features, out_features, bias)
     74         self.in_features = in_features
     75         self.out_features = out_features
---> 76         self.weight = Parameter(torch.Tensor(out_features, in_features))
     77         if bias:
     78             self.bias = Parameter(torch.Tensor(out_features))

TypeError: new() received an invalid combination of arguments - got (float, float), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !float!)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !float!)

**Comment by murthyrudra** [comment]
Hi, I have pushed the code with changes. I have tested the code on `gpu` and it should work now. In case of any issues please let me know.
